name: Build and Release Debian Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          VERSION=$(cat version.txt | sed 's/^v//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Debian package
        uses: docker://ghcr.io/helsinki-systems/build-debian-package:latest
        with:
          entrypoint: /build-debian-package.sh
          args: --git-buildpackage --git-export-dir=/tmp/build --git-upstream-tree=HEAD
        env:
          DEB_EMAIL: "mus@example.com"
          DEB_FULLNAME: "Mus Boulange"

      - name: Rename deb file (remove +dfsg if present)
        run: |
          cd /tmp/build
          for file in *.deb; do
            mv "$file" "${file/+dfsg/}"
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
